#!/usr/bin/env python

import json, sys, os.path
from datetime import datetime

# first arg, script file with web url (lile /local/mycard/mycard.js)
if len(sys.argv) < 2:
    print("Error: first argument must be resource to add (like '/local/mycard/mycard.js')", file=sys.stderr)
    exit(1)

resource=sys.argv[1]
print (f"Adding {resource} as a HomeAssistant frontend resource")

resource_item = {
    "id": str(datetime.now().timestamp()).replace('.', ''),
    "url": resource,
    "type": "module"
}

res_data = None
lovelace_file=os.environ['HA_CONFIG_DIR'] + "/.storage/lovelace_resources"
if os.path.isfile(lovelace_file):
    print (f"Existing lovelace resource file found ({lovelace_file})")
    with open(lovelace_file) as file:
        res_data = json.load(file)
else:
    print (f"Lovelace resource file not found ({lovelace_file}), generating new file")
    res_data = {
        "version": 1,
        "minor_version": 1,
        "key": "lovelace_resources",
        "data": {
            "items": []
        }
    }

res_data["data"]["items"].append(resource_item)

with open(lovelace_file, 'w') as file:
    json.dump(res_data, file, indent=4)
