# default_config for 2023.8.4
# see see manifest file of default_config component to get an updated list

# see https://www.home-assistant.io/integrations/ for info

automation:
counter:
frontend:
homeassistant_alerts:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
person:
schedule:
script:
scene:
timer:
webhook:
zone:

#energy:
#sun:
#system_health:
#application_credentials:
#assist_pipeline:
#bluetooth:
#cloud:
#conversation:
#dhcp:
#hardware:
#history:
#logbook:
#map:
#media_source:
#mobile_app:
#my:
#network:
#ssdp:
#stream:
#tag:
#usb:
#zeroconf:

logger: !include logger.yaml

homeassistant:
  name: Home
  latitude: 57.688219
  longitude: 11.755695
  elevation: 5
  unit_system: metric
  currency: SEK
  country: SE
  time_zone: "Europe/Stockholm"
  legacy_templates: false

#
# included client project yaml (mount from devcontainer.json)
#

