#!/bin/bash

#### USAGE
#
#   * Dockerfile should run: containter setup-container
#   * devcontainer.json should run: containter setup-project (in postCreateCommand)
#   * vscode tasks should
#

set -e

plugins=
user_root=0
user_vscode=1000

[ -n "$DEVIMAGE_DIR" ] || die "DEVIMAGE_DIR not set (set in Dockerfile)"
HA_DEFAULT_CONF_INSTALL=$DEVIMAGE_DIR/homeassistant_default_config



function info(){
    local YELLOW='\033[1;33m'
    local NC='\033[0m' # No Color
    echo -e "${YELLOW}$1${NC}"
}

function errEcho() {
    local RED='\033[0;31m'
    local NC='\033[0m' # No Color
    echo -e "${RED}$1${NC}" 1>&2
}
function die() {
    errEcho "$1" && exit 1 
}

function requireUser() {
 
    if [ "$(id -u)" != "$1" ]; then
        die "Please run as ${1}, not as $(id -u)"
        exit 1
    fi
}

function create_hass_user() {
    local username=${HASS_USERNAME:-dev}
    local password=${HASS_PASSWORD:-dev}
    info "Creating Home Assistant User ${username}:${password}"
    hass --script auth -c ${HA_CONFIG_DIR} add ${username} ${password}
}

function bypass_onboarding() {

    cat > ${HA_CONFIG_DIR}/.storage/onboarding << EOF
{
    "data": {
        "done": [
            "user",
            "core_config",
            "integration"
        ]
    },
    "key": "onboarding",
    "version": 3
}
EOF
}

function install_custom_components() {

    # on the form "Kaptensanders/skolmat" ->   https://github.com/Kaptensanders/skolmat/trunk/custom_components

    if [ -z "$HA_CUSTOM_COMPONENTS" ]; then
        info "No custom components to setup"
        return
    else
        info "Setting up custom components: $HA_CUSTOM_COMPONENTS"
    fi

    mkdir -p $HA_CONFIG_DIR/custom_components

    TMPDIR=/tmp/ha_custom_components
    sudo rm -Rf $TMPDIR
    mkdir $TMPDIR/

    cd $TMPDIR
    for component in $HA_CUSTOM_COMPONENTS
    do
        snv export "https://github.com/${component}/trunk/custom_components"
        mv ./custom_components/* $HA_CONFIG_DIR/custom_components/
        rm -Rf ./custom_components
    done

    cd ..
    rm -Rf $TMPDIR

} 

function fetch_lovelace_plugins() {

    # from @thomasloven

    for plugin in $HA_LOVELACE_PLUGINS
    do
        local author=$(cut -d '/' -f1 <<<"$plugin")
        local repo=$(cut -d '/' -f2 <<<"$plugin")
        local prefix=$(cut -d '-' -f1 <<<"$repo")
        local file

        if [[ $prefix == "lovelace" ]]; then
            file=$(cut -c 10- <<<"$repo")
        else
            file=$repo
        fi

        info "Downloading ${plugin} to ${file}.js"
        curl https://raw.githubusercontent.com/${author}/${repo}/master/dist/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl https://raw.githubusercontent.com/${author}/${repo}/master/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}-bundle.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail
        plugins="${plugins} /local/${file}.js"
    done
}

function install_lovelace_plugins() {

    # from @thomasloven

    for file in $LOVELACE_LOCAL_FILES
    do
        plugins="${plugins} /local/workspace/${file}"
    done

    fetch_lovelace_plugins

    if [ -z "$plugins" ]; then
        info "No Lovelace plugins to setup"
        return
    else
        info "Setting up Lovelace plugins: $plugins"
    fi



    cat > ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
{
    "data": {
        "items": [
EOF

    local i="0"
    for plugin in $plugins
    do
        if [ $i -gt "0" ]; then
            echo "," >> ${HA_CONFIG_DIR}/.storage/lovelace_resources
        fi

        i=$((i+1))

        head -c -1 >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
            {
                "id": "${i}",
                "type": "module",
                "url": "${plugin}"
            }
EOF
    done

    cat >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF

        ]
    },
    "key": "lovelace_resources",
    "version": 1
}
EOF
}

function setup_environment() {

    cat << 'EOF' > /home/vscode/.bash_aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias l='ls -CF'
alias ..='cd ..'
alias p='python3'
alias ha='container hass-run'
alias ha-debug='container hass-debug'
alias halog='tail -n 200 -f ${HA_CONFIG_DIR}/home-assistant.log'
EOF


echo "export HA_CONFIG_DIR=\${HA_CONFIG_DIR:-\"$HA_DEFAULT_CONF_INSTALL\"}" >> /home/vscode/.bashrc
echo "export WORKSPACE_DIR=\${WORKSPACE_DIR:-\"/home/vscode\"}" >> /home/vscode/.bashrc

    cat << 'EOF' >> /home/vscode/.bashrc
export PYTHONPATH="${PYTHONPATH}:${WORKSPACE_DIR}/custom_components"
cd $WORKSPACE_DIR
echo "Devcontainer running:"
echo "* $(python --version)"
echo "* Home Assistant $(cat ${HA_CONFIG_DIR}/.HA_VERSION)" 
echo "* Run 'ha' to start Home Assistant"
EOF
 
    git config --global alias.co checkout
    git config --global alias.br branch
    git config --global alias.ci commit
    git config --global alias.st status
}

function init_ha() {

    # HA seems to have issues on first run to install modules, maybe a race condition issue with pip. Works better second time

    info "Initializing Home Assistant in $HA_CONFIG_DIR"
    local retries="${1:-1}"
    local success=1

    for (( i=0; i<$retries; i++ ))
    do
        if [ "$success" -ne "1" ]; then
            info "\nRetrying HA init...\n"
        fi

        success=1
        coproc (hass -c ${HA_CONFIG_DIR} -v 2>&1;)
        while IFS= read -r line; do
            echo "$line"
            if [[ "$line" == *"[homeassistant.setup] Setup failed for"*  ]]; then
                success=0
                echo "$COPROC_PID Fail"
                
                if [ -n "$COPROC_PID" ]; then # check for pid var first to avoid race condition
                    echo "Kiling $COPROC_PID"
                    kill -INT "$COPROC_PID"
                    wait "$COPROC_PID" || true
                fi
            fi

            if [[ "$line" == *"Starting Home Assistant"* ]]; then
                sleep 3
                kill -INT "$COPROC_PID"
            fi
        done <&"${COPROC[0]}"

        if [ "$success" -eq "1" ]; then
            info "Home Assistant initialization done"
            break
        else
            errEcho "Detected a problem in Homeassistant initialization, aborting..."
        fi

    done
    
    [ "$success" -eq "1" ] || die "Failed to initialize Home assistant"
}

function setup_ha() {

    # homeassistant is already installed by Dockerfile
    
    # perform a default installation in HA_DEFAULT_CONF_INSTALL
    # used to fast track project ha config setup

    info "Installing default HA configuration in $HA_DEFAULT_CONF_INSTALL"

    hass --script ensure_config -c $HA_DEFAULT_CONF_INSTALL
    mkdir -p $HA_DEFAULT_CONF_INSTALL
    HA_CONFIG_DIR=$HA_DEFAULT_CONF_INSTALL init_ha 3
}

function setup_hass_config_dir() {

    info "Setting up hass config dir in $HA_CONFIG_DIR"
    sudo rm -Rf $HA_CONFIG_DIR

    mkdir -p $HA_CONFIG_DIR/custom_components
    mkdir -p $HA_CONFIG_DIR/www
    mkdir -p $HA_CONFIG_DIR/.storage

    # Dockerfile should copy ha_configuration.yaml to DEVIMAGE_DIR
    cp ${DEVIMAGE_DIR}/ha_configuration_base.yaml $HA_CONFIG_DIR/configuration.yaml

    # import contents of .devcontainer/ha_config/ to config dir
    # *.append files are appended to existing files, other files are soft linked
    cd $WORKSPACE_DIR/.devcontainer/ha_config
    for file in *
    do
        target=$HA_CONFIG_DIR/$(basename -s .append $file)
        if [[ $file == *.append ]]; then
            # append to existing
            echo "appending: $file to $target"
            cat $file >> $target
        else
            # link file
            echo "Creating link $target"
            ln -s $PWD/$file $target
        fi
        
    done

    # move the deps folder of the default installation to this config to make it easier to setup hass first time
    info "Bootstrapping $HA_CONFIG_DIR with dependencies from default config installation" 
    mv $HA_DEFAULT_CONF_INSTALL/deps $HA_CONFIG_DIR

    hass --script ensure_config -c $HA_CONFIG_DIR
    echo "$(hass --version)" > $HA_CONFIG_DIR/.HA_VERSION
}

# run from Dockerfile
function setup_container() {

    requireUser $user_vscode

    [ -n "$HA_VERSION" ] || die "HA_VERSION not set"

    setup_ha
    setup_environment
}

# run from devcontainer.json postCreateCommand
# devcontainer.json should set HA_CONFIG_DIR (preferably in ./devcontainer container.env file as --env-file argument to docker run)
function setup_project() {
    
    requireUser $user_vscode

    [ -n "$HA_VERSION" ]    || die "HA_VERSION not set"
    [ -n "$WORKSPACE_DIR" ] || die "WORKSPACE_DIR not set, should be the repository folder"
    [ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set, should typically be WORKSPACE_DIR/ha_config"

    setup_hass_config_dir
    create_hass_user
    bypass_onboarding

    install_custom_components
    install_lovelace_plugins

    info "\nPlease logout and login again to complete setup process\n"

    info "To open a devcontainer and load a .code-workspace directly from command line, see this script:"
    info "https://gist.github.com/Kaptensanders/79da7c1547751fb43c75904e3110bbf9\n"

}

function hass_run() {
    
    requireUser $user_vscode
    # must start from the WORKSPACE_DIR or the PYTHON_PATH wont have any effect (for some reason)
    cd $WORKSPACE_DIR
    hass -v -c $HA_CONFIG_DIR
}

function hass_debug() {

    requireUser $user_vscode
    # must start from the WORKSPACE_DIR or the PYTHON_PATH wont have any effect (for some reason)
    cd $WORKSPACE_DIR
    hass -v -c $HA_CONFIG_DIR --debug
}

case $1 in
    setup-container)
        setup_container
        ;;
    setup-project)
        setup_project
        ;;
    hass-run)
        hass_run
        ;;
    hass-debug)
        hass_debug
        ;;
    *)
        info "Usage: setup_container or setup_project"
        ;;
esac
