#!/bin/bash

#### USAGE
#
#   * Dockerfile should run: containter setup-container
#   * devcontainer.json should run: containter setup-project (in postCreateCommand)
#

set -e

plugins=
user_root=0
user_vscode=1000

[ -n "$HA_DIR" ] || die "HA_DIR not set (set in Dockerfile)"
[ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set (set in Dockerfile)"

function info(){
    local YELLOW='\033[1;33m'
    local NC='\033[0m' # No Color
    echo -e "${YELLOW}$1${NC}"
}

function errEcho() {
    local RED='\033[0;31m'
    local NC='\033[0m' # No Color
    echo -e "${RED}$1${NC}" 1>&2
}
function die() {
    errEcho "$1" && exit 1 
}

function requireUser() {
 
    if [ "$(id -u)" != "$1" ]; then
        die "Please run as ${1}, not as $(id -u)"
        exit 1
    fi
}

function create_hass_user() {
    local username=${HASS_USERNAME:-dev}
    local password=${HASS_PASSWORD:-dev}
    info "Creating Home Assistant User ${username}:${password}"
    venv_run hass --script auth -c ${HA_CONFIG_DIR} add ${username} ${password}
}

function bypass_onboarding() {

    cat > ${HA_CONFIG_DIR}/.storage/onboarding << EOF
{
    "data": {
        "done": [
            "user",
            "core_config",
            "integration"
        ]
    },
    "key": "onboarding",
    "version": 3
}
EOF
}


venv_run() {
  (
    cd "${HA_DIR:?HA_DIR not set}" || exit 1
    ./script/run-in-env.sh "$@"
  )
}

function install_custom_components() {

    # on the form "Kaptensanders/skolmat" ->   https://github.com/Kaptensanders/skolmat/trunk/custom_components

    if [ -z "$HA_CUSTOM_COMPONENTS" ]; then
        info "No custom components to setup"
        return
    else
        info "Setting up custom components: $HA_CUSTOM_COMPONENTS"
    fi

    mkdir -p $HA_CONFIG_DIR/custom_components

    TMPDIR=/tmp/ha_custom_components
    sudo rm -Rf $TMPDIR
    mkdir $TMPDIR/

    cd $TMPDIR
    for component in $HA_CUSTOM_COMPONENTS
    do
        snv export "https://github.com/${component}/trunk/custom_components"
        mv ./custom_components/* $HA_CONFIG_DIR/custom_components/
        rm -Rf ./custom_components
    done

    cd ..
    rm -Rf $TMPDIR

} 

function fetch_lovelace_plugins() {

    # from @thomasloven

    for plugin in $HA_LOVELACE_PLUGINS
    do
        local author=$(cut -d '/' -f1 <<<"$plugin")
        local repo=$(cut -d '/' -f2 <<<"$plugin")
        local prefix=$(cut -d '-' -f1 <<<"$repo")
        local file

        if [[ $prefix == "lovelace" ]]; then
            file=$(cut -c 10- <<<"$repo")
        else
            file=$repo
        fi

        info "Downloading ${plugin} to ${file}.js"
        curl https://raw.githubusercontent.com/${author}/${repo}/master/dist/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl https://raw.githubusercontent.com/${author}/${repo}/master/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}-bundle.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail
        plugins="${plugins} /local/${file}.js"
    done
}

function install_lovelace_plugins() {

    # from @thomasloven

    for file in $HA_LOCAL_LOVELACE_PLUGINS
    do
        plugins="${plugins} /local/${file}"
    done

    fetch_lovelace_plugins

    if [ -z "$plugins" ]; then
        info "No Lovelace plugins to setup"
        return
    else
        info "Setting up Lovelace plugins: $plugins"
    fi



    cat > ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
{
    "data": {
        "items": [
EOF

    local i="0"
    for plugin in $plugins
    do
        if [ $i -gt "0" ]; then
            echo "," >> ${HA_CONFIG_DIR}/.storage/lovelace_resources
        fi

        i=$((i+1))

        head -c -1 >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
            {
                "id": "${i}",
                "type": "module",
                "url": "${plugin}"
            }
EOF
    done

    cat >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF

        ]
    },
    "key": "lovelace_resources",
    "version": 1
}
EOF
}

function setup_environment() {

    info "Setting up user environment..."

    cat << 'EOF' > /home/vscode/.bash_aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias l='ls -CF'
alias ..='cd ..'
alias p='python3'
alias ha='hass -v -c ${HA_CONFIG_DIR}'
alias ha-debug='hass -v -c ${HA_CONFIG_DIR} --debug '
alias halog='tail -n 200 -f ${HA_CONFIG_DIR}/home-assistant.log'
EOF

# set default values for HA_CONFIG_DIR and WORKSPACE_DIR if they are not set by a devcontainer.json (.env file). This way we can run the default vanilla HA in the docker image
echo "export HA_CONFIG_DIR=\${HA_CONFIG_DIR:-\"/home/vscode/ha_config\"}" >> /home/vscode/.bashrc
echo "export WORKSPACE_DIR=\${WORKSPACE_DIR:-\"/workspaces\"}" >> /home/vscode/.bashrc

    cat << 'EOF' >> /home/vscode/.bashrc
source ~/ha_core/.venv/bin/activate
export PYTHONPATH="${PYTHONPATH}:${WORKSPACE_DIR}"
cd $HA_CONFIG_DIR
echo "Devcontainer running:"
echo "* $(python --version)"
echo "* HA config dir: ${HA_CONFIG_DIR}"
echo "* Home Assistant $(cat ${HA_CONFIG_DIR}/.HA_VERSION)" 
echo "* Run 'ha' to start Home Assistant as http://localhost:8123"
cd $WORKSPACE_DIR
EOF
 
    git config --global alias.co checkout
    git config --global alias.br branch
    git config --global alias.ci commit
    git config --global alias.st status

}

function setup_vanilla_ha() {

    info "Configuring Home Assistant vanilla install..."

    # set default config so HA starts in vanilla mode, will be overridden by setup_hass_config_dir
    
    echo "default: info" > $HA_CONFIG_DIR/logger.yaml
    cat << 'EOF' > $HA_CONFIG_DIR/homeassistant.yaml
name: Home
latitude: 57.688219
longitude: 11.755695
elevation: 5
unit_system: metric
currency: SEK
country: SE
time_zone: "Europe/Stockholm"
legacy_templates: false
EOF

    # some extra dependencies
    venv_run pip install zlib_ng isal

    echo "$(venv_run hass --version)" > $HA_CONFIG_DIR/.HA_VERSION
    venv_run hass --script ensure_config -c $HA_CONFIG_DIR

    mkdir -p $HA_CONFIG_DIR/custom_components
    mkdir -p $HA_CONFIG_DIR/www
    mkdir -p $HA_CONFIG_DIR/.storage

    create_hass_user
    bypass_onboarding

    coproc HA { venv_run hass -v -c "$HA_CONFIG_DIR" 2>&1; }
    ha_pid=$HA_PID

    while IFS= read -r line <&"${HA[0]}"; do
        echo "$line"
        if [[ "$line" == *"Starting Home Assistant"* ]]; then
            info "HA initialization done, stopping HA in 10 seconds..."
            sleep 10
            kill "$ha_pid" 2>/dev/null || true
            break
        fi
    done

    set +e
    wait "$ha_pid"
    set -e
}

function setup_hass_config_dir() {

    info "Setting up hass config dir in $HA_CONFIG_DIR"

    # import contents of .devcontainer/ha_config/ to config dir
    # *.append files are appended to existing files, other files are soft linked
    cd $WORKSPACE_DIR/.devcontainer/ha_config
    for file in *
    do
        target=$HA_CONFIG_DIR/$(basename -s .append $file)
        if [[ $file == *.append ]]; then
            # append to existing
            echo "appending: $file to $target"
            cat $file >> $target
        else
            # link file
            echo "Creating link $target"
            ln -sf $PWD/$file $target
        fi
        
    done
}

# run from Dockerfile
function setup_container() {

    requireUser $user_vscode

    [ -n "$HA_VERSION" ] || die "HA_VERSION not set"

    setup_vanilla_ha
    setup_environment
}

# run from devcontainer.json postCreateCommand
# devcontainer.json should set HA_CONFIG_DIR (preferably in ./devcontainer container.env file as --env-file argument to docker run)
function setup_project() {
    
    requireUser $user_vscode

    [ -n "$HA_VERSION" ]    || die "HA_VERSION not set"
    [ -n "$WORKSPACE_DIR" ] || die "WORKSPACE_DIR not set, should be the repository folder"
    [ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set, should typically be /home/vscode/ha_config"

    setup_hass_config_dir
    install_custom_components
    install_lovelace_plugins

    info "\nPlease logout and login again to complete setup process\n"

    info "To open a devcontainer and load a .code-workspace directly from command line, see this script:"
    info "https://gist.github.com/Kaptensanders/79da7c1547751fb43c75904e3110bbf9\n"

    # run project specific setup file if exists

    if test -f "$WORKSPACE_DIR/.devcontainer/setup-project"; then
        $WORKSPACE_DIR/.devcontainer/setup-project
    else
        echo "project specific setup file not found, skipping..."
    fi

}

case $1 in
    setup-container)
        setup_container
        ;;
    setup-project)
        setup_project
        ;;
    *)
        info "Usage: setup_container or setup_project"
        ;;
esac
