#!/bin/bash

plugins=

function ensure_hass_config() {
    hass --script ensure_config -c /config
}

function create_hass_user() {
    local username=${HASS_USERNAME:-dev}
    local password=${HASS_PASSWORD:-dev}
    echo "Creating Home Assistant User ${username}:${password}"
    hass --script auth -c /config add ${username} ${password}
}

function bypass_onboarding() {
    cat > /config/.storage/onboarding << EOF
{
    "data": {
        "done": [
            "user",
            "core_config",
            "integration"
        ]
    },
    "key": "onboarding",
    "version": 3
}
EOF
}

function fetch_lovelace_plugins() {
    mkdir -p /config/www/workspace
    for plugin in $LOVELACE_PLUGINS
    do
        local author=$(cut -d '/' -f1 <<<"$plugin")
        local repo=$(cut -d '/' -f2 <<<"$plugin")
        local prefix=$(cut -d '-' -f1 <<<"$repo")
        local file

        if [[ $prefix == "lovelace" ]]; then
            file=$(cut -c 10- <<<"$repo")
        else
            file=$repo
        fi

        echo "Downloading ${plugin} to ${file}.js"
        curl https://raw.githubusercontent.com/${author}/${repo}/master/dist/${file}.js --output /config/www/${file}.js --fail \
        || curl https://raw.githubusercontent.com/${author}/${repo}/master/${file}.js --output /config/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}.js --output /config/www/${file}.js --fail \
        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}-bundle.js --output /config/www/${file}.js --fail
        plugins="${plugins} /local/${file}.js"
    done
}

function install_lovelace_plugins() {
    for file in $LOVELACE_LOCAL_FILES
    do
        plugins="${plugins} /local/workspace/${file}"
    done

    fetch_lovelace_plugins

    cat > /config/.storage/lovelace_resources << EOF
{
    "data": {
        "items": [
EOF

    local i="0"
    for plugin in $plugins
    do
        if [ $i -gt "0" ]; then
            echo "," >> /config/.storage/lovelace_resources
        fi

        i=$((i+1))

        head -c -1 >> /config/.storage/lovelace_resources << EOF
            {
                "id": "${i}",
                "type": "module",
                "url": "${plugin}"
            }
EOF
    done

    cat >> /config/.storage/lovelace_resources << EOF

        ]
    },
    "key": "lovelace_resources",
    "version": 1
}
EOF
}

function install_hacs() {
    cd /config
    curl -sfSL https://get.hacs.xyz | bash -
}

function install_ha_dev() {

    local VERSION=${HA_VERSION:-dev}
    echo "Installing Home Assistant $VERSION in /usr/src/homeassistant"

    rm -rf /usr/src/homeassistant
    git clone --branch $VERSION --single-branch --depth 1 https://github.com/home-assistant/core.git /usr/src/homeassistant
    git config --global --add safe.directory /usr/src/homeassistant

    pip install --upgrade -e /usr/src/homeassistant
    
    echo "$(hass --version)" > /config/.HA_VERSION
}

function make_hass_config() {
    # add extra config from project conf file
    echo "Adding extra configuration..."
}

function fix_env() {

    cat << EOF > /home/vscode/.bash_aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias l='ls -CF'
alias ..='cd ..'
alias p='python3'
alias ha='sudo hass -c /config -v'
alias halog='tail -f /config/homeassistant.log'
EOF
   
    sudo chown vscode:vscode /home/vscode/.bash_aliases

    cat << EOF >> /home/vscode/.bashrc

echo "Devcontainer running:"
echo "* $(python --version)"
echo "* Home Assistant $(hass --version)" 
EOF
    git config --global alias.co checkout
    git config --global alias.br branch
    git config --global alias.ci commit
    git config --global alias.st status
}

function setup() {
    install_ha_dev
    make_hass_config
    ensure_hass_config
    create_hass_user
    bypass_onboarding
    install_hacs
    install_lovelace_plugins
    fix_env
}

function run() {
    hass -c /config -v
}

if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
fi

case $1 in
    setup)
        setup
        ;;
    launch-hass)
        run
        ;;
    *)
        echo "Use with setup or launch-hass"
        ;;
esac