#!/bin/bash

#HA_VERSION=2025.1.0
HA_VERSION=2025.7.0
IMAGE_NAME=hass_dev_image_${HA_VERSION}
CONTAINER_NAME=hass_devcontainer_${HA_VERSION}
HASS_PORT=8123

function build() {
    docker build $1 --build-arg HA_VERSION=${HA_VERSION} --progress=plain --tag "$IMAGE_NAME" . 
    docker image prune -f
}

function create_container() {
    docker container rm $CONTAINER_NAME 2>/dev/null
    docker run -it \
        -p $HASS_PORT:8123 \
        -v $(pwd):/workspaces/hass-custom-container \
        --name "$CONTAINER_NAME" \
        "$IMAGE_NAME" $1
}

function test_remote() {
    docker run --rm -it \
        -p $HASS_PORT:8123 \
        -v $(pwd):/workspaces/hass-custom-container \
        --name ${CONTAINER_NAME}_remote\
        kaptensanders/hass-custom-devcontainer
}

case $1 in
    build)
        build
        ;;
    rebuild)
        build --no-cache
        ;;
    create-container)
        create_container /bin/bash
        ;;
    recreate)
        build --no-cache
        create_container
        ;;
    build-and-run)
        build
        create_container /bin/bash
        ;;
    login)
        docker start $CONTAINER_NAME >/dev/null 2>&1 && echo "Starting $CONTAINER_NAME" && STOP_CONTAINER=1
        docker exec -it $CONTAINER_NAME /bin/bash
        [ -n "$STOP_CONTAINER" ] && echo "Stopping $CONTAINER_NAME" && docker stop $CONTAINER_NAME
        ;;
    run-hass)
        docker start $CONTAINER_NAME >/dev/null 2>&1 && echo "Starting $CONTAINER_NAME" && STOP_CONTAINER=1
        docker exec -it $CONTAINER_NAME /bin/bash -ic ha
        [ -n "$STOP_CONTAINER" ] && echo "Stopping $CONTAINER_NAME" && docker stop $CONTAINER_NAME
        ;;
    container-start)
        docker start $CONTAINER_NAME
        ;;
    container-stop)
        docker stop $CONTAINER_NAME
        ;;
    test-remote)
        test_remote
        ;;
    *)
        echo "helper <build, rebuild, create-container, recreate, build-and-run, login, container-start, container-stop ,test-remote>"
        echo "  * build-and-run:"
        echo "      - same as build and create_container"
        echo "  * build:"
        echo "      - build new $IMAGE_NAME image (cached if available)"
        echo "      - delete old dangling image"
        echo "  * rebuild:"
        echo "      - same as 'build' but without cached build"
        echo "  * create_container:"
        echo "      - delete container $CONTAINER_NAME"
        echo "      - build and run new $CONTAINER_NAME"
        echo "  * login:"
        echo "      - start $CONTAINER_NAME and attach login shell"
        echo "  * test_hass:"
        echo "      - same as build and create_container separatly"
        echo "  * test_container:"
        echo "      - local build and create_container but do not run hass, login to bash instead"
        echo "  * testremote:"
        echo "      - run container pulled from dockerhub"
        ;;
esac