#!/bin/bash

IMAGE_NAME=hass_dev_image
CONTAINER_NAME=hass_dev_container
HASS_PORT=8123

function build() {
    docker build $1 --progress=plain --tag "$IMAGE_NAME" . 
    docker image prune -f
}

function create_container() {
    docker container rm $CONTAINER_NAME 2>/dev/null
    docker run -it \
        -p $HASS_PORT:8123 \
        -v $(pwd):/workspaces/hass-custom-container \
        --name "$CONTAINER_NAME" \
        "$IMAGE_NAME" $1
}

function test_remote() {
    docker run --rm -it \
        -p $HASS_PORT:8123 \
        -v $(pwd):/workspaces/hass-custom-container \
        --name ${CONTAINER_NAME}_remote\
        kaptensanders/hass-custom-devcontainer
}

case $1 in
    build)
        build
        ;;
    rebuild)
        build --no-cache
        ;;
    create_container)
        create_container /bin/bash
        ;;
    recreate)
        build --no-cache
        create_container
        ;;
    login)
        docker start hass_dev_container >/dev/null 2>&1
        docker exec -it $CONTAINER_NAME /bin/bash
        ;;
    test_hass)
        build
        create_container
        ;;
    test_container)
        build
        create_container /bin/bash
        ;;
    test_remote)
        test_remote
        ;;
    *)
        echo "toolbox <build, rebuild, create_container, recreate, login, test, test_remote>"
        echo "  * build:"
        echo "      - build new $IMAGE_NAME image (cached if available)"
        echo "      - delete old dangling image"
        echo "  * rebuild:"
        echo "      - same as 'build' but without cached build"
        echo "  * create_container:"
        echo "      - delete container $CONTAINER_NAME"
        echo "      - build and run new $CONTAINER_NAME"
        echo "  * login:"
        echo "      - start $CONTAINER_NAME and attach login shell"
        echo "  * test_hass:"
        echo "      - same as build and create_container separatly"
        echo "  * test_container:"
        echo "      - local build and create_container but do not run hass, login to bash instead"
        echo "  * testremote:"
        echo "      - run container pulled from dockerhub"
        ;;
esac